Added apache license header to source files, changes README and LICEN…
devicehive/devicehive-admin-console pull request #29
Opened 2016-11-25 09:53 UTC by BoldinovaNatalya

…SE files

2016-11-25 10:03 UTC, zubrabubra requested changes
Lets see

2016-11-25 10:03 UTC, zubrabubra commented on README.md
> +&copy; Copyright 2013 DataArt Apps &copy; All Rights Reserved
@BoldinovaNatalya @iilunin @tmatvienko @aleksey-suprun i think we need to keep 2015, and should not change to 2013.

2016-11-28 09:59 UTC, oleksii-suprun approved these changes

2016-12-01 09:43 UTC, zubrabubra approved these changes

2016-12-01 09:43 UTC, merged